<h1 class="page-header">Edycja oferty</h1>
<div class="col-lg-6">
<form role="form">
    <div class="form-group">
        <label>Produkt:</label>
                <input class="form-control" placeholder="Produkt"/>
    </div>
    <div class="form-group">
        <label>Ilość:</label>
                <input class="form-control" placeholder="Ilość"/>
    </div>       
    <div class="form-group">
        <label>Data rozpoczęcia:</label>
        <input type ="date"/>
    </div>
    <div class="form-group">
        <label>Data zakończenia:</label>
        <input type ="date"/>
    </div>
                <a href="<?= $this->url('uzytkownik',array()); ?>"><button type="submit" class="btn btn-default">Zatwierdź</button></a>
                <button type="reset" class="btn btn-default">Wyczyść</button>

</form>
</div>


<!--
<h1>Uaktualnianie oferty</h1>

<form>
    <table style="border:1px solid;">
        <tr>
            <td>
                Produkt:
            </td>
            <td>
                <input type="text" value="Aspirin"/>
            </td>
        </tr>
        <tr>
            <td>
                Ilość:
            </td>
            <td>
                <input type="text" value="100"/>
            </td>
        </tr>
        <tr>
            <td>
                Data rozpoczęcia:
            </td> 
            <td>
                <input type="date" value="2014-01-12"/>
            </td>
        </tr>
        <tr>
            <td>
                Data Zakończenia
            </td> 
            <td>
                <input type="date" value="2015-05-25"/>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <a href="<?= $this->url('oferta',array()); ?>"><button>Zatwierdź</button></a>
            </td>
        </tr>
    </table>
</form>
-->