<form class="form-inline" role="form" method="post">
    <div class="form-group">
        <label for="search">Szukaj</label>
        &nbsp;
        <input type="text" class="form-control" name="szukaj" id="search">
    </div>
    &nbsp;
    &nbsp;
    <div class="form-group">
        <label>Wyszukaj po</label>
        &nbsp;
        <select class="form-control" name="wyszukaj_po">
            <option>wszystkie pola</option>
            <option>produkt</option>
            <option>data rozpoczęcia</option>
            <option>data zakończenia</option>
        </select>
    </div>
    &nbsp;
    &nbsp;
    <button type="submit" class="btn btn-default">Szukaj</button>
</form>

<br/>

<div class="col-lg-12">
    <div class="table-responsive"> 
        <table class="table table-bordered table-hover table-striped">
            <thead> 
    <tr>
        <th>
            Lp.
        </th>
        <th>
            Produkt
        </th>
        <th>
            Ilość
        </th>
        <th>
            Data rozpoczęcia
        </th>
        <th>
            Data zakończenia
        </th>
        <th>
            Zaznacz
        </th>
    </tr>
            </thead>
    <?php foreach ($okazje as $okazja) : ?>
    <tr>
    <td><?= $this->escapeHtml($okazja['id_oferta']) ?></td>
    <td><?= $this->escapeHtml($okazja['produkt']) ?></td>
    <td><?= $this->escapeHtml($okazja['ilosc']) ?></td>
    <td><?= $this->escapeHtml($okazja['oferta_obo_od']) ?></td>
    <td><?= $this->escapeHtml($okazja['oferta_obo_do']) ?></td>
    <td><input type="checkbox"/></td>
    </tr>
<?php endforeach; ?>
    <!--
    <tr>
        <td>
            1
        </td>
        <td>
            Aspirin
        </td>
        <td>
            100
        </td>
        <td>
            12.01.2014
        </td>
        <td>
            25.05.2015
        </td>
        <td>
            <input type="checkbox"/>
        </td>
    </tr>
    <tr>
        <td>
            2
        </td>
        <td>
            Ehinacea
        </td>
        <td>
            1234
        </td>
        <td>
            11.11.2011
        </td>
        <td>
            12.12.2012
        </td>
        <td>
            <input type="checkbox"/>
        </td>
    </tr>
    <tr>
        <td>
            3
        </td>
        <td>
            Gripex noc
        </td>
        <td>
            37
        </td>
        <td>
            19.11.2014
        </td>
        <td>
            22.12.2014
        </td>
        <td>
            <input type="checkbox"/>
        </td>
    </tr>
    <tr>
        <td>
            4
        </td>
        <td>
            Rutinoscorbin
        </td>
        <td>
            150
        </td>
        <td>
            13.12.2015
        </td>
        <td>
            17.01.2016
        </td>
        <td>
            <input type="checkbox"/>
        </td>
    </tr>
    -->
    
</table>
</div>

<br/>

<a href="<?= $this->url('oferta',array('action' => 'dodaj')); ?>"><button class="btn btn-default">Nowy</button></a>
<a href="<?= $this->url('oferta',array('action' => 'edytuj')); ?>"><button class= "btn btn-default">Edytuj</button></a>
<button  class= "btn btn-default">Usuń</button>

<!--
<a href="<?= $this->url('oferta',array('action' => 'dodaj')); ?>"><button>Nowa</button></a>&nbsp;&nbsp;
<a href="<?= $this->url('oferta',array('action' => 'edytuj')); ?>"><button>Edytuj</button></a>&nbsp;&nbsp;
<button>Usuń</button>&nbsp;&nbsp;
-->