<style type="text/css">
a {
 color: black;
 text-decoration: none;
}
a:hover {
 color: silver;
 text-decoration: underline;
}
</style>

<div class="row">
                    <div class="col-lg-12">
                          <div class="table-responsive" >
                              <br/>
                              <br/>
                              <br/>
                            <table class="table table-bordered table-hover table-striped" >
                                <thead>
                                    <tr class="active">                             
                                        <th><a href="<?= $this->url('statystyka',array('action' => 'oferta')); ?>">Oferta</a></th>
                                        <th><a href="<?= $this->url('statystyka',array('action' => 'produkt')); ?>">Produkt</a></th>
                                        <th><a href="<?= $this->url('statystyka',array('action' => 'promocja')); ?>">Promocja</a></th>
                                        <th><a href="<?= $this->url('statystyka',array('action' => 'uzytkownik')); ?>">Uzytkownik</a></th>
                                    </tr>
                                </thead>                                
                            </table>
                        </div>
                    </div>
</div>
