<h1 class="page-header">Dodawanie promocji</h1>
<div class="col-lg-6">
<form role="form">
    <div class="form-group">
        <label>Nazwa:</label>
                <input class="form-control" placeholder="Nazwa"/>
    </div>
    <div class="form-group">
        <label>Typ promocji:</label>
                <input class="form-control" placeholder="Typ promocji"/>
    </div>       
    <div class="form-group">
        <label>Ważna od:</label>
        <input type ="date"/>
    </div>
    <div class="form-group">
        <label>Ważna do:</label>
        <input type ="date"/>
    </div>
    <div class="form-group">
        <label>Reguła promocji:</label>
                <input class="form-control" placeholder="Reguła promocji"/>
    </div>
                <a href="<?= $this->url('uzytkownik',array()); ?>"><button type="submit" class="btn btn-default">Zatwierdź</button></a>
                <button type="reset" class="btn btn-default">Wyczyść</button>

</form>
</div>




<!--
<h1>Dodawanie promocji</h1>
<form>
    <table style="border:1px solid;">
        <tr>
            <td>
                Nazwa:
            </td>
            <td>
                <input type="text"/>
            </td>
        </tr>
        <tr>
            <td>
                Typ promocji:
            </td>
            <td>
                <input type="text"/>
            </td>
        </tr>
        <tr>
            
        </tr>

        <tr>
            <td>
                Ważna od:
            </td>
            <td>
                <input type="text"/>
            </td>
        </tr>
                <tr>
            <td>
                Ważna do:
            </td>
            <td>
                <input type="text"/>
            </td>
        </tr>
        <tr>
            <td>
                Reguła promocji:
            </td> 
            <td>
                <input type="text"/>&nbsp;&nbsp;
            </td>
        </tr>
        
        <tr>
            <td></td>
            <td>
                <a href="<?= $this->url('produkt',array()); ?>"><button>Zatwierdź</button></a>
            </td>
        </tr>
    </table>
</form>
-->