<form class="form-inline" role="form" method="post">
    <div class="form-group">
        <label for="search">Szukaj</label>
        &nbsp;
        <input type="text" class="form-control" name="szukaj" id="search">
    </div>
    &nbsp;
    &nbsp;
    <div class="form-group">
        <label>Wyszukaj po</label>
        &nbsp;
        <select class="form-control" name="wyszukaj_po">
            <option>wszystkie pola</option>
            <option>ważna od</option>
            <option>ważna do</option>
            <option>typ promocji</option>
        </select>
    </div>
    &nbsp;
    &nbsp;
    <button type="submit" class="btn btn-default">Szukaj</button>
</form>

<br/>


<!--nowy widok-->

<div class="col-lg-12">
    <div class="table-responsive">
        <table  class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Promocja</th>
                    <th>Produkt</th>
                    <th>Typ promocji</th>
                    <th>Ważna od</th>
                    <th>Ważna do</th>
                    <th>Zasada promocji</th>
                    <th>Zaznacz</th>

                </tr>
            </thead>
            
            <?php foreach ($promocje as $promocja) : ?>
                <tr>
                    <td><?= $this->escapeHtml($promocja['id_promocja']) ?></td>
                    <td><?= $this->escapeHtml($promocja['produkt']) ?></td>
                    <td><?= $this->escapeHtml($promocja['typ']) ?></td>
                    <td><?= $this->escapeHtml($promocja['obowiazuje_od']) ?></td>
                    <td><?= $this->escapeHtml($promocja['obowiazuje_do']) ?></td>
                    <td><?= $this->escapeHtml($promocja['regula']) ?></td>
                   
                    <td><input type="checkbox"/></td>
                </tr>
            <?php endforeach; ?>

        </table>
    </div>
</div>


<!--
<br/>
<br/>
<div class="col-lg-12">
<div class="table-responsive">
<table  class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Nazwa produktu</th>
        <th>Typ promocji</th>
        <th>Ważna od</th>
        <th>Ważna do</th>
        <th>Zasada promocji</th>
        <th>Zaznacz</th>
        
    </tr>
    </thead>
    
        <tr>
        <td>1</td>
        <td>Aspiryna</td>
        <td>Typ promocji</td>
        <td>01.01.2014</td>
        <td>01.12.2014</td>
        <td>-15%</td>
        <td>
                <input type="checkbox"/>
            </td>
       
    </tr>  
</table>
</div>
</div>
-->

<br/>
<br/>
<a href="<?= $this->url('promocja', array('action' => 'dodaj')); ?>"><button class="btn btn-default">Nowy</button></a>&nbsp;&nbsp;
<button class="btn btn-default">Usuń</button>&nbsp;&nbsp;
<a href="<?= $this->url('promocja', array('action' => 'edytuj')); ?>"><button class="btn btn-default">Edytuj</button></a>