<h1 class="page-header">Edycja produktu</h1>
<div class="col-lg-6">
    <form action="<?= $this->url('produkt', array('action' => 'edytuj', 'id' => $produkt->id_produktu)); ?>" method="post">
        <div class="form-group">
            <label>Nazwa:</label>
            <input class="form-control" name="Nazwa" value="<?= $produkt->nazwa_produktu; ?>" placeholder="Nazwa"/>
        </div>
        <div class="form-group">
            <label>Opis:</label>
            <textarea class="form-control" name="Opis" rows="3"><?= $produkt->opis; ?></textarea>
        </div>
        <div class="form-group">
            <label>Zdjęcie:</label>
            <input type="file" onchange="readURL(this);">
            <img style="width:100px;height:100px;" id="blah" src="#" alt="your image">
            <!--<img style="width:50px;height:50px;" id="blah" src="#" alt="your image">-->
        </div>
        <div class="form-group">
            <label>Cena:</label>
            <input class="form-control" name="Cena" value="<?= $produkt->cena_jednostkowa; ?>" placeholder="Cena"/>
        </div>
    <!-- JAREK WRZUCI TU IKONY: -->
        <div class="form-group input-group">
            <label>Tagi:</label>
            <input type="text" class="form-control" name="Tagi" value="<?= $produkt->tagi; ?>" placeholder="Tag">
            <span class="input-group-btn"><button class="btn btn-default" type="button"><i class="fa fa-search"></i></button></span>
        </div>
        <div class="form-group input-group">
            <label>Zamienniki:</label>
            <input type="text" class="form-control" name="Zamienniki" value="<?= $produkt->zamienniki; ?>" placeholder="Zamiennik">
            <span class="input-group-btn"><button class="btn btn-default" type="button"><i class="fa fa-search"></i></button></span>
        </div>

        <input type="hidden" name="Id_produktu" value="<?= $produkt->id_produktu; ?>" placeholder="Id_produktu">
        <button type="submit" class="btn btn-default">Zatwierdź</button>
        <button type="reset" class="btn btn-default">Wyczyść</button>
    </form>
</div>

<script>
         function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result);
                
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

<!--
<h1>Uaktualnianie</h1>

<form>
    <table style="border:1px solid;">
        <tr>
            <td>
                Nazwa:
            </td>
            <td>
                <input type="text" value="Rutinoscorbin"/>
            </td>
        </tr>
        <tr>
            <td>
                Opis:
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <textarea rows="8" cols="45">Czujesz się niewyraźnie? Rutinoscorbin jest najlepszym lekiem na grypę i przeziębienie!</textarea>
            </td>
        </tr>
        <tr>
            <td>
                Zdjecie:
            </td>
            <td>
                <input type='file' onchange="readURL(this);" />
            </td>
        </tr>
        <tr>
            <td>
                <img style="width:100px;height:100px;" id="blah" src="/projekt/public/img/produkty/rutinoscorbin.jpg" alt="your image" />
            </td>
        </tr>
        <tr>
            <td>
                Cena:
            </td>
            <td>
                <input type="text" value="10,00 zł"/>
            </td>
        </tr>
        <tr>
            <td>
                Tagi:
            </td> 
            <td>
                <input type="text" value="grypa"/>&nbsp;&nbsp;<button>+</button>
            </td>
        </tr>
        <tr>
            <td>
                Zamienniki
            </td> 
            <td>
                <input type="text" value="Gripex"/>&nbsp;&nbsp;<button>+</button>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <a href="<?= $this->url('produkt',array()); ?>"><button>Zatwierdź</button></a>
            </td>
        </tr>
    </table>
</form>

<script>
         function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result);
                
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>
-->