<h1 class="page-header">Dodawanie użytkownika</h1>
<div class="col-lg-6">
<form role="form">
    <div class="form-group">
        <label>Imię i nazwisko:</label>
                <input class="form-control" placeholder="Imię i nazwisko"/>
    </div>
    <div class="form-group">
        <label>Adres:</label>
                <input class="form-control" placeholder="Adres"/>
    </div>       
    <div class="form-group">
        <label>Telefon</label>
                <input class="form-control" placeholder="Telefon"/>
    </div>
    <div class="form-group">
        <label>E-mail:</label>
                <input class="form-control" placeholder="E-mail"/>
    </div>
                <a href="<?= $this->url('uzytkownik',array()); ?>"><button type="submit" class="btn btn-default">Zatwierdź</button></a>
                <button type="reset" class="btn btn-default">Wyczyść</button>

</form>
</div>