<h1 class="page-header">Edycja użytkownika</h1>
<div class="col-lg-6">
<form role="form">
    <div class="form-group">
        <label>Imię i nazwisko:</label>
                <input class="form-control" placeholder="Imię i nazwisko"/>
    </div>
    <div class="form-group">
        <label>Adres:</label>
                <input class="form-control" placeholder="Adres"/>
    </div>       
    <div class="form-group">
        <label>Telefon</label>
                <input class="form-control" placeholder="Telefon"/>
    </div>
    <div class="form-group">
        <label>E-mail:</label>
                <input class="form-control" placeholder="E-mail"/>
    </div>
                <a href="<?= $this->url('uzytkownik',array()); ?>"><button type="submit" class="btn btn-default">Zatwierdź</button></a>
                <button type="reset" class="btn btn-default">Wyczyść</button>

</form>
</div>



<!--
<h1>Edytowanie użytkownika</h1>

<form>
    <table style="border:1px solid;">
        <tr>
            <td>
                Imię i nazwisko:
            </td>
            <td>
                <input type="text" value="Marek Kowalski" />
            </td>
        </tr>
        <tr>
            <td>
                Adres:
            </td>
            <td>
                <input type="text" style="width: 200px" value="Rzeszów, ul. Krakowska 45" />
            </td>
        </tr>
        <tr>
            <td>
                Telefon:
            </td>
            <td>
                <input type="text" value="+48 788695258" />
            </td>
        </tr>
        <tr>
            <td>
                E-mail:
            </td>
            <td>
                <input type="text" value="mkow@wp.pl" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <a href="<?= $this->url('uzytkownik',array()); ?>"><button>Zatwierdź</button></a>
            </td>
        </tr>
    </table>
</form>
-->