<?php echo $this->doctype(); ?>

<html lang="pl">
    <head>
        
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('SPM'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) 
			->prependStylesheet($this->basePath() . '/css/sb-admin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ?>
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('produkt'); ?>">SPM</a>
                </div>
                <ul class="nav navbar-right top-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Jan Kowalski <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#"><i class="fa fa-fw fa-user"></i> Profil</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-fw fa-gear"></i> Ustawienia</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#"><i class="fa fa-fw fa-power-off"></i> Wyloguj</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav side-nav">
                        <li class="<?php if ($this->page == 1) { echo 'active'; }?>">
                            <a href="<?= $this->url('produkt',array()); ?>"><i class="fa fa-fw fa-cube"></i> Produkty</a>
                        </li>
                        <li class="<?php if ($this->page == 2) { echo 'active'; }?>">
                            <a href="<?= $this->url('oferta',array()); ?>"><i class="fa fa-fw fa-shopping-cart"></i> Oferty</a>
                        </li>
                        <li class="<?php if ($this->page == 3) { echo 'active'; }?>">
                            <a href="<?= $this->url('promocja',array()); ?>"><i class="fa fa-fw fa-dollar"></i> Promocje</a>
                        </li>
                        <li class="<?php if ($this->page == 4) { echo 'active'; }?>">
                            <a href="<?= $this->url('uzytkownik',array()); ?>"><i class="fa fa-fw fa-users"></i> Użytkownicy</a>
                        </li>
                        <li class="<?php if ($this->page == 5) { echo 'active'; }?>">
                            <a href="<?= $this->url('statystyka',array()); ?>"><i class="fa fa-fw fa-bar-chart-o"></i> Statystyki</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div id="page-wrapper">
                <div class="container-fluid">

                <!-- Page Heading -->
                    <div class="row">
                        <div class="col-lg-12">
                            <?php echo $this->content; ?>
                        </div>
                    </div>
                <!-- /.row -->

                </div>
            <!-- /.container-fluid -->

            </div>

        </div> <!-- /container -->
    </body>
</html>
